# Generated by Django 5.2.9 on 2025-12-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_address_institution_endereco_fisico'),
        ('medprofiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofessional',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='institution',
            field=models.ManyToManyField(related_name='professionals', to='institution.institution'),
        ),
    ]
