# Generated by Django 5.2.9 on 2025-12-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='tipo',
        ),
        migrations.AddField(
            model_name='institution',
            name='itype',
            field=models.CharField(choices=[('C', 'Clinica'), ('H', 'Hospital'), ('UM', 'Unidade Móvel')], default='H', max_length=2),
        ),
    ]
