# Generated by Django 5.2.9 on 2025-12-10 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_alter_institution_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=120)),
                ('cep', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='endereco_fisico',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.address'),
        ),
    ]
