# Generated by Django 5.2.9 on 2026-01-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
