# Generated by Django 5.2.9 on 2026-01-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_alter_institution_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution/static'),
        ),
    ]
