# Generated by Django 6.0.1 on 2026-01-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0009_alter_institution_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution/static'),
        ),
    ]
