# Generated by Django 5.2.9 on 2025-12-24 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('institution', '0005_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mammogramexam',
            name='acceptance_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mammogramexam',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
        migrations.AddField(
            model_name='mammogramexam',
            name='user_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
