# Generated by Django 6.0.1 on 2026-01-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_mammogramexam_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mammogramexam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mammograms/'),
        ),
        migrations.AlterField(
            model_name='mammogramexam',
            name='itype',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PRONTO', 'Laudo Pronto'), ('ENTREGUE', 'Laudo Entregue'), ('CANCELADO', 'Laudo Cancelado')], default='PENDENTE', max_length=9),
        ),
        migrations.AlterField(
            model_name='mammogramexam',
            name='result',
            field=models.CharField(choices=[('SAUDAVEL', 'Saudavel'), ('BENIGNO', 'Benigno'), ('MALIGNO', 'Maligno'), ('INDETERMINADO', 'Indeterminado')], default='SAUDAVEL', max_length=50),
        ),
    ]
