# Generated by Django 5.2.9 on 2025-12-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_remove_institution_tipo_institution_itype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='site',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
