# Generated by Django 6.0.1 on 2026-01-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_mammogramexam_acceptance_term_mammogramexam_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mammogramexam',
            name='itype',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('READY', 'Laudo Pronto'), ('DELIVERED', 'Laudo Entregue'), ('CANCELED', 'Laudo Cancelado')], default='PENDING', max_length=9),
        ),
    ]
