# Generated by Django 5.2.9 on 2025-12-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='rg',
        ),
    ]
