# Generated by Django 5.2.9 on 2025-12-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_rg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mammogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mammogram', models.ImageField(upload_to='mammogram/')),
            ],
        ),
    ]
