# Generated by Django 5.2.9 on 2025-12-21 01:46

import builtins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_mammogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mammogram',
            name='mammogram',
        ),
        migrations.AddField(
            model_name='mammogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mammograms/'),
        ),
        migrations.AddField(
            model_name='mammogram',
            name='patient',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, related_name='mammograms', to='patients.patient'),
            preserve_default=False,
        ),
    ]
